name: base_flutter_bloc_pattem
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Service locator
  get_it: ^7.2.0
  #  Bloc
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  # Bloc for state management
  flutter_bloc: ^8.1.2
  # support for API
  retrofit: ^4.0.1
  dio: ^5.0.3
  json_annotation: ^4.8.0
  pretty_dio_logger: ^1.3.1
  # Functional programming thingies
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.3
  # storage
  shared_preferences: ^2.0.20
  # Toast message
  fluttertoast: ^8.2.1
  # language location
  easy_localization: ^3.0.1
  # login_SNS
  #  firebase_auth: ^3.3.0
  #  firebase_core: ^1.10.2
  #  google_sign_in: ^5.4.0
  #  flutter_facebook_auth: ^4.4.0+1
  #  sign_in_with_apple: ^4.0.0

  #svg image
  flutter_svg: ^2.0.4
  #auto resize
  sizer: ^2.0.15
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # support API service
  retrofit_generator: any
  json_serializable: ^6.6.1
  build_runner: any
  analyzer: ^5.10.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/
